/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package session02_baitap;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author TAI
 */
public final class CountDownTimer extends javax.swing.JFrame {

    /**
     * Creates new form CountDownTimer
     */
    int timeCountDown;
    Timer timer;

    public CountDownTimer() {
        initComponents();
        btnStop.setEnabled(false);
        prgbarCountDown.setStringPainted(true);
        prgbarCountDown.setString("0 seconds");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStop = new javax.swing.JButton();
        btnCountDown = new javax.swing.JButton();
        prgbarCountDown = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        sliderMinutes = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Count Down Timer");
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        btnStop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnCountDown.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCountDown.setText("Count Down");
        btnCountDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountDownActionPerformed(evt);
            }
        });

        prgbarCountDown.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Minutes");

        sliderMinutes.setMajorTickSpacing(10);
        sliderMinutes.setMaximum(10);
        sliderMinutes.setMinorTickSpacing(1);
        sliderMinutes.setPaintLabels(true);
        sliderMinutes.setPaintTicks(true);
        sliderMinutes.setSnapToTicks(true);
        sliderMinutes.setToolTipText("");
        sliderMinutes.setValue(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sliderMinutes, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCountDown)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop))
                    .addComponent(prgbarCountDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCountDown, btnStop});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCountDown, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderMinutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                .addComponent(prgbarCountDown, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCountDown, btnStop});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCountDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountDownActionPerformed
        // TODO add your handling code here:
        if (sliderMinutes.getValue() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose minute to count down", "Information", JOptionPane.INFORMATION_MESSAGE);
            sliderMinutes.requestFocus();
            return;
        } else {
            sliderMinutes.setEnabled(false);
            btnCountDown.setEnabled(false);
            btnStop.setEnabled(true);
            timeCountDown = 60 * sliderMinutes.getValue();
            prgbarCountDown.setMinimum(0);
            prgbarCountDown.setMaximum(60 * sliderMinutes.getValue());
            prgbarCountDown.setValue(timeCountDown);

            timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    timeCountDown--;
                    prgbarCountDown.setValue(timeCountDown);
                    prgbarCountDown.setString(prgbarCountDown.getValue() + " seconds");
                    if (timeCountDown == 0) {
                        timer.stop();
                        JOptionPane.showMessageDialog(null, "Time out! ", "Information", JOptionPane.INFORMATION_MESSAGE);
                        sliderMinutes.setEnabled(true);
                        btnCountDown.setEnabled(true);
                        btnStop.setEnabled(false);
                    }
                }
            });
            timer.start();

        }
    }//GEN-LAST:event_btnCountDownActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        timer.stop();
        btnCountDown.setEnabled(true);
        sliderMinutes.setEnabled(true);
        btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountDownTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountDownTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountDownTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountDownTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountDownTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCountDown;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar prgbarCountDown;
    private javax.swing.JSlider sliderMinutes;
    // End of variables declaration//GEN-END:variables
}
